name: segcal
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9
  - pytorch-cuda=11.6
  - pytorch=1.13.0
  - torchvision
  - fire
  - matplotlib
  - opencv
  - pytorch-lightning
  - pytorch3d
  - scipy
  - shapely
  - tqdm
  - wandb